INSERT INTO recipes
(title, image, description, time, ingredients, instructions)
VALUES
('Garlic Shrimp Pasta Bake', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F4518035.jpg', 'Want a super creamy,  satisfying, quick and easy dinner? Then this buttery garlic shrimp pasta bake is definitely a family pleasing meal idea that you should try!', '45 minutes', '1 teaspoon vegetable oil, 1 (10 ounce) package penne pasta, 3 tablespoons butter cubed, 1 tablespoon minced garlic, 1 pound uncooked medium shrimp peeled and deveined, 3 tablespoons chopped fresh parsley divided, 2 teaspoons chopped fresh dill, 2 tablespoons all-purpose flour, 1/2 cup chicken broth, 1 cup milk, 2 large tomatoes chopped, 1 tablespoon lemon juice, 1 teaspoon salt, 1 teaspoon black pepper, 3/4 cup grated parmesan cheese, 1/2 cup grated romano cheese, 1/4 cup shredded mozzarella cheese', 'Step 1: Preheat the oven to 350 degrees F (175 degrees C)., Step 2: Bring a large pot of lightly salted water to a boil, add penne and cook stirring occasionally for 8 minutes or until al dente, then drain., Step 3: Heat 1 tablespoon butter and vegetable oil in large oven safe skillet over medium heat, Add garlic; cook until fragrant then add shrimp, 2 tablespoons parsley, and dill. Cook and stir, flipping shrimp halfway, until light pink and then move shrimp on a plate and set aside., Step 4: Melt the remaining 2 tablespoons butter in the same skillet, add flour whisk until fully combined and starting to turn golden. Add chicken broth and milk and whisk to combine. Stir in tomatoes, lemon juice, salt, and pepper. Bring to a simmer., Step 5: Stir 1/2 cup Parmesan and Romano cheese until cheese begins to melt and sauce starts to get creamy. Add 1 tablespoon mozzarella cheese. Mix in penne and shrimp, then top with remaining parsley, Parmesan, and mozzarella., Step 6: Bake in the preheated oven and bake until top is golden should take about 10 minutes and enjoy!' ),
('Chicken Parmesan', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F43%2F2022%2F03%2F19%2F223042-Chicken-Parmesan-mfs_003.jpg', 'A beautiful panko crusted chicken breast with the most amazing marinara sauce and fresh mozzarella. Yes Please!!', '45 minutes', '4  skinless boneless chicken breast halves, salt and black pepper to taste, 2 large eggs, 1 cup panko bread crumbs or more as needed, 3/4 cup grated parmesan cheese divided, 2 tablespoons flour or more as needed, 1/2 cup olive oil for frying or as needed, 1/2 cup marinara sauce, 1/4 cup fresh mozzarella cut into small cubes, 1/4 cup  chiffonade fresh basil, 1/2 cup grated provolone cheese, 2 teaspoons olive oil', 'Step 1: Preheat oven to 450 degrees F (230 degrees C)., Step 2: Place chicken breasts between two sheets of heavy plastic wraps spaced about 5 inches apart on a solid, level surface. Firmly pound chicken with the smooth side of a meat mallet to a thickness of 1/2 inch and then season chicken with salt and pepper., Step 3: Beat eggs in a shallow bowl and set aside. Mix bread crumbs and 1/2 cup Parmesan cheese in a separate bowl and set aside. Place flour in a sifter or strainer and sprinkle over chicken breasts evenly coating both sides., Step 4: Dip the flour coated chicken breast in beaten eggs on both sides and then transfer to bread crumb mixture pressing crumbs into both sides. Repeat with remaining chicken breasts and then let chicken rest for 10 to 15 minutes., Step 5: Heat 1/2 inch olive oil in a large skillet over medium heat until it begins to shimmer. Cook chicken for 2 minutes on each side., Step 6: Transfer chicken to a baking dish and top with 2 tablespoons marinara and then top with provolone cheese, fresh basil, and fresh mozzarella. Finally sprinkle remaining Parmesan cheese over top and drizzle each piece with 1/2 teaspoon olive oil., Step  7: Bake in the preheated oven until cheese is bubbly and lightly golden about 15 to 20 minutes and Enjoy!'),
('Oven-Roasted Asparagus', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F43%2F2022%2F04%2F18%2F214931_oven-roasted-asparagus_Rita-1x1-1.jpg', 'Salty and savory, the roasting method kills the natural bitterness of asparagus. Serves as an excellent side dish with grilled fish or lamb. Oh La La!', '20 minutes', '1 bunch thin asparagus trimmed, 3 tablespoons olive oil, 1 1/2 tablespoons grated Parmesan cheese (Optional), 1 clove garlic minced finely, 1 teaspoon sea salt, 1/2 teaspoon black pepper, 1 tablespoon lemon juice (Optional)', 'Step 1: Preheat oven to 425 degrees F (220 degrees C)., Step 2: Place asparagus into mixing bowl, and drizzle with olive oil. Toss together with Parmesan cheese, garlic, salt, and pepper. Then arrange the asparagus onto a baking sheet in a single layer., Step 3: Bake in preheated oven until tender it should take about 12 to 15 minutes depending on the thickness of the asparagus. Finally drizzle with lemon juice just before serving and enjoy!'),
('Perfect Sushi Rice', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F43%2F2022%2F04%2F22%2F99211-Perfect-sushi-rice-mfs-076-1x1-1.jpg', 'Always wondered how to make the most delicious sushi rice? Well here is the best recipe ever!', '25 minutes', '2 cups uncooked glutinous white rice, 3 cups of water, 1/2 cup rice vinegar, 1 tablespoon vegetable oil, 1/4 cup white sugar, 1 teaspoon salt', 'Step 1: Rinse the rice in a strainer or colander under cold running water until the water runs clear., Step 2: Combine rice and water in a saucepan over medium-high heat and bring to a boil. Reduce heat to low, cover, and cook until rice is tender and all water has been absorbed, about 15 to 20 minutes. Remove from stove and set aside until cool enough to handle., Step 3: Meanwhile, combine rice vinegar, oil, sugar, and salt in a small saucepan over medium heat. Cook until the sugar has dissolved. Allow to cool, then stir into the cooked rice. While mixture will appear wet at first, keep stirring and rice will dry as it cools and then enjoy!'),
('Chewy Flourless Peanut Butter Cookies', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F2271991.jpg', '20 minutes', '1 cup peanut butter, 1/2 cup white sugar, 1/3 cup packed brown sugar, 1 egg, 1 teaspoon vanilla extract, 1/2 teaspoon baking soda, 1/2 cup semisweet chocolate chips (Optional)', 'Step 1: Preheat oven to 350 degrees F (175 degrees C)., Step 2: Beat peanut butter, white sugar, and brown sugar together in a large bowl with an electric mixer until smooth. Stir in egg, vanilla extract, and backing soda into peanut butter mixture and then stir in chocolate chips., Step 3: Drop mixture by small rounded spoonfuls onto baking sheet about 3 inches apart., Step 4: Bake in the preheated oven until cookies are flattened and golden about 8-10 minutes and enjoy!');

INSERT INTO cut_styles
(name, image, description)
VALUES
('Batonnet', 'https://www.simplehomecookedrecipes.com/wp-content/uploads/2021/02/Batonette-Cut-1-1024x683.png', 'In French, batonnet translates to little stick and is often used as a starting point for other cuts, especially a small dice. A true batonnet cut measures ¼-inch by ¼-inch and is about 2 to 3 inches long.'),
('Allumette Jardiniere', 'https://1.bp.blogspot.com/-gSCtMuSA9cE/YSX_5B0s_zI/AAAAAAAACZU/MYYjYWHZaagLArzGT6JGj002l3OdL4RCQCLcBGAsYHQ/s1920/Julienne-min.png', 'To allumette a vegetable means to cut it into small, thin pieces the size of matchsticks. If the vegetable is to be cooked, an allumette cut allows for a vegetable to cook rapidly and evenly, and integrate well into a mix of other ingredients, for instance in a sauce.'),
('Julienne', 'https://arbuz.com/wp-content/uploads/2018/11/How-To-Julienne-10.jpg', 'Julienne is a French cooking term for thin strips of vegetables (or meat or fruit). The strips are usually about 3 inches long and 1/16- to 1/8-inch thick.'),
('Rough Julienne', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTXcmAQWh_GGoZ9DTMsvxEvNeExWfuetoXnw&usqp=CAU', 'Rough Julienne is the shape and technique of cutting exactly the same as Julienne, but thicker. The length of a slice is up to 1.5 inches, thickness - from 2.7 to 3.9 inches.'),
('Macedoine / Large Dice', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxV5Tgx4HSHY0Yh41nesV5dJYdQ8Spdo8rmVwqeMPpYHtUDbJq6XSTiuAPH4PDSmQjOHc&usqp=CAU', 'A term used to describe the process of dicing ingredients into 3/4 inch cubes or a term that is used to describe a preparation of fruits or vegetables that have been diced (cubes that are 3/4 inch square) to be served either cold (raw) or hot (cooked).'),
('Medium Dice', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxV5Tgx4HSHY0Yh41nesV5dJYdQ8Spdo8rmVwqeMPpYHtUDbJq6XSTiuAPH4PDSmQjOHc&usqp=CAU', 'A term used to describe the process of dicing ingredients into 1/2 inch cubes or a term that is used to describe a preparation of fruits or vegetables that have been diced (cubes that are 1/2 inch square) to be served either cold (raw) or hot (cooked).'),
('Small Dice', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOXTjyFKpVTGSsWQLO4slv7vqhCxL8-zdo5hYCAs-OZDXrg5zZDXlMmxeUlSxyc72yynQ&usqp=CAU', 'A term used to describe the process of dicing ingredients into 1/4 inch cubes or a term that is used to describe a preparation of fruits or vegetables that have been diced (cubes that are 1/4 inch square) to be served either cold (raw) or hot (cooked).'),
('Paysanne', 'https://i.pinimg.com/originals/6b/b2/f1/6bb2f1b1e003a62637749587123cffea.jpg', 'A French term that is used to describe vegetables that have been cut into thin slices with shapes that correspond best to the shape of the vegetable.'),
('Chiffonade', 'https://theinspiredhome.imgix.net/images/chiffonade-knife-cuts.jpg?crop=focalpoint&fit=crop&fm=webp&fp-x=0.5&fp-y=0.5&q=80&w=845', 'To chiffonade is to cut thin strips of a flat leafy vegetable or larger leaf herb. It is a cutting technique that you can use with things like lettuces and very commonly basil, and it results in sliver-like curled strips that look very elegant when mixed into or strewn over various dishes.'),
('Rondelle / Slice', 'https://img.buzzfeed.com/buzzfeed-static/static/2019-01/4/10/asset/buzzfeed-prod-web-01/sub-buzz-15984-1546615417-1.jpg?resize=625:417', 'Also called rounds, a type of cut that creates round or oval, flat pieces by cutting a cylindrical vegetable crosswise. A regular crosswise cut produces a round slice and if the cut is made at an angle, it produces an oval slice.'),
('Diagonal / Oval Slice', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYP-SzTXc4s7RGAhy1vVGnHhdvISJBjWZXiw&usqp=CAU', 'Diagonal Cut. When diagonal cutting, the knife enters at a 45 ° angle. This method reduces cooking time because more surface is exposed to the heat, ensuring tenderness and an attractive shape.'),
('Brunoise / Mince', 'https://cdn.jwplayer.com/v2/media/7DNMRjKh/poster.jpg?width=720', 'The brunoise is the finest dice and is derived from the julienne. Any smaller and the cut is considered a mince. To brunoise, gather the julienned vegetable strips together, then dice into even 3mm cubes. This cut is most often used for making sauces like tomato concasse or as an aromatic garnish on dishes.'),
('Rolling Cut', 'https://res.cloudinary.com/hksqkdlah/image/upload/STP_KitchenNotes_HowToMakeARollCut_1437_hwihqw.jpg', 'Roll-cutting is used for long vegetables, such as Asian eggplant, carrots, and zucchini. It makes attractive chunks and exposes more of the surface area of the vegetable for faster cooking.'),
('Tourne', 'https://files.recipetips.com/images/glossary/t/tournee_cut_carrots.jpg', 'Tournée is French for the word turned and refers to a method of cutting and peeling root vegetables into oblong, seven-sided football-like shapes. The cut can be used for vegetables like carrots, turnips, and parsnips, or even zucchini and other types of summer squash.'),
('Mirepoix', 'https://theforkedspoon.com/wp-content/uploads/2019/11/11-02-19-2.jpg', 'Mirepoix (pronounced meer-uh-pwa) is a simple mix of coarsely chopped vegetables, onions, carrots and celery, the holy trinity of French cuisine. Many soups, sauces, stews, stocks and other dishes begin with mirepoix as the first building block of flavor.'),
('Crush', 'https://assets.epicurious.com/photos/5519aa9a6ec924e9311ce0c1/master/w_2106,h_1404,c_limit/EP-20150330-garlic-6x4-hires.jpg', 'A term used when piling the vegetable on one side of the board. Tilt the knife at a 30-degree angle to the board and drag it over the vegetable, scraping it across the surface of the board. Pile up the vegetable again, sprinkle lightly with salt, and scrape again. Repeat once or twice until the vegetable is a smooth paste.'),
('Wedges', 'https://www.stephgaudreau.com/wp-content/uploads/2019/05/roasted-potato-wedges-2.jpg', 'A term use to cut spherical vegetables and fruits lengthwise in sixths or eighths. Giving the vegetable or fruit a half u shape in appearance.'),
('Slit / Split', 'https://s3.amazonaws.com/finegardening.s3.tauntoncloud.com/app/uploads/vg-migration/2008/07/27233815/kg11-prepping_leeks-01.jpg', 'A term used when slicing the vegetable or fruit in half, mostly used for vegetable such as leeks, fennel, and string beans.');

INSERT INTO knives
(name, image, description)
VALUES
('Chef Knife', 'https://cdn.healthykitchen101.com/uploads/2018/02/The-Chef-Knives.jpg?w=1200&q=75', 'Also called a cooks knife, this is the most important blade in your kitchen. This knife typically has a broad blade tapering upward to a point, allowing it to rock back and forth for fast mincing. It can be anywhere between 6 and 12 inches long and the size is often chosen with consideration to how big the cooks hands are. The chef knife can be used for almost every cutting task in the kitchen, from cutting chicken to chopping carrots. That is why it is the must-have item in every kitchen knife set collection.'),
('Santoku Knife', 'https://cdn.healthykitchen101.com/uploads/2020/07/Santoku-Knife.jpg?w=1200&q=75', 'The Santoku knife is a Japanese version of the Western-style chefs knife. It is slightly shorter and thinner, and is used in place of the chefs knife by some cooks, especially those who prefer a smaller, lighter blade. Santoku means three virtues, which are slicing, dicing, and mincing. This knife is an all-rounder and can do almost everything a typical chefs knife can. Due to a flat blade, it does not rock on the cutting board. This makes it less suited for when you want to mince herbs, but a better choice for skinny slices of veggies.'),
('Utility Knife', 'https://cdn.healthykitchen101.com/uploads/2018/02/The-Utility-Knife.jpg?w=1200&q=75', 'Measuring between 4 and 7 inches in length, the utility knife is usually used for cutting food that is too small for a chefs knife. It is not great for chopping or slicing large items, but the narrow blade and small tip allows it to handle tasks such as thinner slicing, trimming, and filleting even better than a chefs knife.'),
('Kitchen Shears', 'https://cdn.healthykitchen101.com/uploads/2018/02/The-Kitchen-Shears.jpg?w=1200&q=75', 'Though shears are not technically a type of knives, they can be used in place of a knife. Kitchen shears are a pair of scissors with thick and strong blades to handle various food materials. They are useful for snipping herbs, sectioning chicken, preparing shrimp, octopus, and many other cutting tasks. For many home cooks, they are a favorite for slicing pizza. Some shears designed specifically for fast cutting of green onion or other herbs may have more than one blade. However, the blades on those shears are usually thin and weak. They also take more effort to sharpen than ordinary shears, which themselves are already picky about what type of knife sharpeners work on them.'),
('Boning Knife', 'https://cdn.healthykitchen101.com/uploads/2018/02/A-Boning-Knife.jpg?w=1200&q=75', 'The boning knife, as its name suggests, is used for separating meat from the bone, filleting fish, and cutting up meat. Smaller boning knives can also be used in place of a paring knife for peeling and trimming veggies. Boning knives are typically about 3 to 8 inches in length, with slightly varying blade widths. The blades can be Flexi, Semi-Flexi, or stiff, with stiff blades being the most popular among home cooks due to the enhanced precision of the cut.'),
('Bread Knife', 'https://cdn.healthykitchen101.com/uploads/2018/02/The-Bread-Knife.jpg?w=1200&q=75', 'Bread knives are used for cutting bread, cakes, and sometimes meat, poultry, and seafood. They are designed in a way that allows you to saw through the bread without pushing down or squishing it. Made to cut large chunks of food, the bread knife belongs to the longer spectrum of kitchen knives. It can be between 7 and 10 inches long. Its blade is narrow and straight (i.e. having no belly), and is always serrated, with big teeth along it.'),
('Cleaver Knife', 'https://cdn.healthykitchen101.com/uploads/2018/02/The-Cleaver-Knife.jpg?w=1200&q=75', 'A typical cleaver has a full tang, a thick spine and a very wide blade with little or no belly. This design allows it to cut through bones, meat, and hard and thick materials such as squash or pumpkin in a chopping motion. With a wide and heavy blade, the cleaver is also ideal for beating and pulverizing meat, poultry and fish, and crushing garlic.'),
('Paring Knife', 'https://cdn.healthykitchen101.com/uploads/2018/02/A-Paring-Knife.jpg?w=1200&q=75', 'If you love making garnishes for your food and drinks, the paring knife is a must-have. A paring knife usually comes with a thin 3 to 4 inch blade with a pointed tip. It can be used for cutting and peeling fruits and veggies, and trimming excess fat with great precision. The most common styles of paring knives include the spear point, sheeps foot, and birds beak, named after the shape of the tip.'),
('Steak Knife', 'https://cdn.healthykitchen101.com/uploads/2018/02/The-Steak-Knife.jpg?w=1200&q=75', 'Also called table knives, they are small knives that are used at the table for cooked food. They are great for steak, chicken, and fish. Steak knives can come with serrated, semi-serrated, or non-serrated edges. Serrated steak knives stay sharp for a longer period of time without honing or sharpening. Non-serrated knives become dull faster, but they are also easier to sharpen.'),
('Nakiri Bocho Knife', 'https://cdn.healthykitchen101.com/uploads/2018/02/The-Nakiri-Bocho.jpg?w=1200&q=75', 'The Nakiri bocho is a Japanese style knife used mostly for cutting vegetables. It features a thin and wide blade and squared-off tips. As it is designed for chopping veggies, the knife has a long straight blade. This allows it to cut long vegetables (eggplants or carrots, for example) in half with ease. It is the knife you should use when you want to make thin slices out of cucumber, bitter gourd, or tomatoes.'),
('Fillet Knife', 'https://cdn.healthykitchen101.com/uploads/2018/02/The-Fillet-Knife.jpg?w=1200&q=75', 'This knife looks very similar to the boning knife. However, there are subtle differences between the two. Since a boning knife is designed to remove meat from the bone, it tends to be thicker and have better force endurance. The fillet knife, meanwhile, is made to cut thin fish slices and thus is typically thinner, longer, and more flexible. The distinctions are so small the two knives can substitute each other in most cases. Knife makers sometimes blend the two, hence the emergence of the boning fillet knife. If you are an expert in sashimi or chicken boning, you would probably notice the differences. Other than that, either of the two should be sufficient for casual home cooking.');

INSERT INTO pots_pans
(name, image, description)
VALUES
(),
();

INSERT INTO cooking_styles
(name, image, description)
VALUES
(),
();
