INSERT INTO recipes
(title, image, description, time, ingredients, instructions)
VALUES
('Garlic Shrimp Pasta Bake', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F4518035.jpg', 'Want a super creamy,  satisfying, quick and easy dinner? Then this buttery garlic shrimp pasta bake is definitely a family pleasing meal idea that you should try!', '45 minutes', '1 teaspoon vegetable oil, 1 (10 ounce) package penne pasta, 3 tablespoons butter cubed, 1 tablespoon minced garlic, 1 pound uncooked medium shrimp peeled and deveined, 3 tablespoons chopped fresh parsley divided, 2 teaspoons chopped fresh dill, 2 tablespoons all-purpose flour, 1/2 cup chicken broth, 1 cup milk, 2 large tomatoes chopped, 1 tablespoon lemon juice, 1 teaspoon salt, 1 teaspoon black pepper, 3/4 cup grated parmesan cheese, 1/2 cup grated romano cheese, 1/4 cup shredded mozzarella cheese', 'Step 1: Preheat the oven to 350 degrees F (175 degrees C)., Step 2: Bring a large pot of lightly salted water to a boil, add penne and cook stirring occasionally for 8 minutes or until al dente, then drain., Step 3: Heat 1 tablespoon butter and vegetable oil in large oven safe skillet over medium heat, Add garlic; cook until fragrant then add shrimp, 2 tablespoons parsley, and dill. Cook and stir, flipping shrimp halfway, until light pink and then move shrimp on a plate and set aside., Step 4: Melt the remaining 2 tablespoons butter in the same skillet, add flour whisk until fully combined and starting to turn golden. Add chicken broth and milk and whisk to combine. Stir in tomatoes, lemon juice, salt, and pepper. Bring to a simmer., Step 5: Stir 1/2 cup Parmesan and Romano cheese until cheese begins to melt and sauce starts to get creamy. Add 1 tablespoon mozzarella cheese. Mix in penne and shrimp, then top with remaining parsley, Parmesan, and mozzarella., Step 6: Bake in the preheated oven and bake until top is golden should take about 10 minutes and enjoy!' ),
('Chicken Parmesan', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F43%2F2022%2F03%2F19%2F223042-Chicken-Parmesan-mfs_003.jpg', 'A beautiful panko crusted chicken breast with the most amazing marinara sauce and fresh mozzarella. Yes Please!!', '45 minutes', '4  skinless boneless chicken breast halves, salt and black pepper to taste, 2 large eggs, 1 cup panko bread crumbs or more as needed, 3/4 cup grated parmesan cheese divided, 2 tablespoons flour or more as needed, 1/2 cup olive oil for frying or as needed, 1/2 cup marinara sauce, 1/4 cup fresh mozzarella cut into small cubes, 1/4 cup  chiffonade fresh basil, 1/2 cup grated provolone cheese, 2 teaspoons olive oil', 'Step 1: Preheat oven to 450 degrees F (230 degrees C)., Step 2: Place chicken breasts between two sheets of heavy plastic wraps spaced about 5 inches apart on a solid, level surface. Firmly pound chicken with the smooth side of a meat mallet to a thickness of 1/2 inch and then season chicken with salt and pepper., Step 3: Beat eggs in a shallow bowl and set aside. Mix bread crumbs and 1/2 cup Parmesan cheese in a separate bowl and set aside. Place flour in a sifter or strainer and sprinkle over chicken breasts evenly coating both sides., Step 4: Dip the flour coated chicken breast in beaten eggs on both sides and then transfer to bread crumb mixture pressing crumbs into both sides. Repeat with remaining chicken breasts and then let chicken rest for 10 to 15 minutes., Step 5: Heat 1/2 inch olive oil in a large skillet over medium heat until it begins to shimmer. Cook chicken for 2 minutes on each side., Step 6: Transfer chicken to a baking dish and top with 2 tablespoons marinara and then top with provolone cheese, fresh basil, and fresh mozzarella. Finally sprinkle remaining Parmesan cheese over top and drizzle each piece with 1/2 teaspoon olive oil., Step  7: Bake in the preheated oven until cheese is bubbly and lightly golden about 15 to 20 minutes and Enjoy!'),
('Oven-Roasted Asparagus', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F43%2F2022%2F04%2F18%2F214931_oven-roasted-asparagus_Rita-1x1-1.jpg', 'Salty and savory, the roasting method kills the natural bitterness of asparagus. Serves as an excellent side dish with grilled fish or lamb. Oh La La!', '20 minutes', '1 bunch thin asparagus trimmed, 3 tablespoons olive oil, 1 1/2 tablespoons grated Parmesan cheese (Optional), 1 clove garlic minced finely, 1 teaspoon sea salt, 1/2 teaspoon black pepper, 1 tablespoon lemon juice (Optional)', 'Step 1: Preheat oven to 425 degrees F (220 degrees C)., Step 2: Place asparagus into mixing bowl, and drizzle with olive oil. Toss together with Parmesan cheese, garlic, salt, and pepper. Then arrange the asparagus onto a baking sheet in a single layer., Step 3: Bake in preheated oven until tender it should take about 12 to 15 minutes depending on the thickness of the asparagus. Finally drizzle with lemon juice just before serving and enjoy!'),
('Perfect Sushi Rice', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F43%2F2022%2F04%2F22%2F99211-Perfect-sushi-rice-mfs-076-1x1-1.jpg', 'Always wondered how to make the most delicious sushi rice? Well here is the best recipe ever!', '25 minutes', '2 cups uncooked glutinous white rice, 3 cups of water, 1/2 cup rice vinegar, 1 tablespoon vegetable oil, 1/4 cup white sugar, 1 teaspoon salt', 'Step 1: Rinse the rice in a strainer or colander under cold running water until the water runs clear., Step 2: Combine rice and water in a saucepan over medium-high heat and bring to a boil. Reduce heat to low, cover, and cook until rice is tender and all water has been absorbed, about 15 to 20 minutes. Remove from stove and set aside until cool enough to handle., Step 3: Meanwhile, combine rice vinegar, oil, sugar, and salt in a small saucepan over medium heat. Cook until the sugar has dissolved. Allow to cool, then stir into the cooked rice. While mixture will appear wet at first, keep stirring and rice will dry as it cools and then enjoy!'),
('Chewy Flourless Peanut Butter Cookies', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F2271991.jpg', 'A simple and easy recipe that is amazing and delicious. Be careful when making these one bite and BAM! The whole plate is gone!!', '20 minutes', '1 cup peanut butter, 1/2 cup white sugar, 1/3 cup packed brown sugar, 1 egg, 1 teaspoon vanilla extract, 1/2 teaspoon baking soda, 1/2 cup semisweet chocolate chips (Optional)', 'Step 1: Preheat oven to 350 degrees F (175 degrees C)., Step 2: Beat peanut butter, white sugar, and brown sugar together in a large bowl with an electric mixer until smooth. Stir in egg, vanilla extract, and backing soda into peanut butter mixture and then stir in chocolate chips., Step 3: Drop mixture by small rounded spoonfuls onto baking sheet about 3 inches apart., Step 4: Bake in the preheated oven until cookies are flattened and golden about 8-10 minutes and enjoy!'),
('Chicken Pot Pie', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F43%2F2022%2F03%2F09%2F26317-chicken-pot-pie-mfs-481.jpg', 'An authentic recipe that every cook needs to have in their repertoire. Just like grandma used to make definitely a family favorite!', '80 minutes', '1 pound skinless boneless chicken breasts cubed, 1 cup diced carrots, 1 cup frozen green peas, 1/2 cup diced celery, 1/3 cup butter, 1/3 cup diced white onion, 1/3 cup all-purpose flour, 1/2 teaspoon salt, 1/4 teaspoon black pepper, 1/4 teaspoon celery seed, 1 3/4 cups chicken broth, 2/3 cup milk, 2 (9 inch) unbaked pie crusts', 'Step 1: Preheat oven to 425 degrees F (220 degrees C)., Step 2: Combine chicken, carrots, peas, and celery in a saucepan; add water to cover and bring to a boil. Boil for 15 minutes, then remove from heat and drain., Step 3: While the chicken is cooking, melt butter in another saucepan over medium heat. Add onion and cook until soft and semi-translucent about 5 to 7 minutes. Stir in flour, salt, pepper, and celery seed. Slowly stir in chicken broth and milk. Reduce heat to medium-low and simmer until thick, about 5 to 10 minutes. Remove from heat and set aside., Step 4: Place chicken and vegetables in the bottom of pie crust. Pour hot liquid mixture over top. Cover with top crust, seal the edges, and cut away any excess dough. Make several small slits in the top crust to allow steam to escape., Step 5: Bake in the preheated oven until pastry is golden brown and filling is bubbly, about 30 to 35 minutes. Cool for 10 mintues before serving and enjoy!'),
('Simple Macaroni and Cheese', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F43%2F2022%2F03%2F19%2F238691-Simple-Macaroni-And-Cheese-mfs_006.jpg', 'Quick, easy, and extremely tasty what more can you ask for! Fancy designer mac and cheese often is expensiveto make because of the exotic and expensive cheeses but often do not taste very good. That is why we are keeping it simple with this recipe!', '25 minutes', '1 (8 ounce) box elbow macaroni, 1/4 cup butter, 1/4 cup all-purpose flour, 1/2 teaspoon salt, ground black pepper to taste, 2 cups milk, 2 cups shredded sharp cheddar cheese, 1/2 cup shredded provolone cheese, 1/2 cup grated parmesan cheese', 'Step 1: Bring a large pot of salted water (should taste like the sea) to a boil. Cook elbow macaroni in the boiling water, stirring occasionally until cooked through but firm to the bite, about 7 to 9 minutes., Step 2: At the same time, melt butter in a saucepan over medium heat. Add flour, salt, and pepper and stir until smooth, about 4 to 5 minutes. Pour in milk slowly, while stirring continuously. Continue to cook and stir until mixture is smooth and bubbling, about 5 minutes making sure the milk does not burn., Step 3: Add cheeses slowly and stir until melted, about 3 to 4 minutes., Step 4: Drain macaroni and add to cheese mixture, fold pasta in until well coated and enjoy!'),
('Chicago-Inspired Italian Beef Sandwich', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F1100724.jpg', 'A combination between a traditional beef sandwich and french dip sandwich with a little nod to a pulled pork sandwich. Once you make this tasty creation you will keep coming back for more!', '85 minutes', '1 1/2 pounds boneless beef chuck cut into 2 inch pieces, salt and ground black pepper to taste, 1 tablespoon vegetable oil, 6 cloves garlic sliced, 2 tablespoons white vinegar, 1 tablespoon dried oregano, 1 teaspoon dried thyme, 1 teaspoon dried rosemary, 3 bay leaves, 1/4 teaspoon red pepper flakes, 4 cups chicken broth, 4 chibatta rolls sliced in half, 1 cup diced giardiniera, 2 teaspoons minced fresh parsley', 'Step 1: Season beef with salt and black pepper. Heat vegetable oil in a heavy pot over high heat. Cook and stir beef in the hot oil until browned, about 5 to 8 minutes., Step 2: Stir garlic, vinegar, oregano, 1 teaspoon salt, thyme, rosemary, 1 teaspoon black pepper, bay leaves, and red pepper flakes into beef. Add the chicken broth and bring to a simmer. Cover pot with a lid, reduce heat to low, and simmer until meat is fork-tender, about 60 minutes., Step 3: Transfer meat to a separate pot and add 1/4 cup of the broth to it. Use a wooden spoon to gently break meat into smaller chunks. Cover and set aside for now., Step 4: Skim excess grease from top of broth that is remaining in the first pot. Season with salt and pepper to taste and bring back to medium heat and reduce until it is about half the original amount., Step 5: Toast chibatta rolls and lay halves on a work surface and add 2 to 3 tablespoons of the reduces broth over each half of bread. Add generous portion of meat to the bottom half of the bread and add a spoonful of giardiniera on top of the meat and place top half of the bread. Repeat with the remaining 3 breads., Step 6: Spoon reduced broth into ramekins and top each ramekin with a little bit of the parsley, serve with sandwiches and enjoy!'),
('Broiled Lobster Tails', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F43%2F2022%2F08%2F08%2F34638-BrioledLobsterTails-ddmfs-1x1-0073-1.jpg', 'Cooking lobster tails under the broiler is a quick and tasty way to make delicious lobster tails! Keep an eye on these broiled lobster tails while they are in the oven so they do not burn.', '20 minutes', '2 whole lobster tails, 1/2 cup melted butter, 1/2 teaspoon ground paprika, salt and ground white pepper to taste, 1 lemon cut into wedges', 'Step 1: Preheat the broiler., Step 2: Place lobster tails on a baking sheet. With a sharp knife or kitchen shears, carefully cut the top side of lobster shells lengthwise. Pull apart shells slightly, and season meat with equal amounts of melted butter, paprika, salt, and white pepper., Step 3: Broil lobster tails until lightly browned and lobster meat is opaque, about 5 to 10 minutes. Garnish with lemon wedge to serve and enjoy!!');

INSERT INTO cut_styles
(name, image, description)
VALUES
('Batonnet', 'https://www.simplehomecookedrecipes.com/wp-content/uploads/2021/02/Batonette-Cut-1-1024x683.png', 'In French, batonnet translates to little stick and is often used as a starting point for other cuts, especially a small dice. A true batonnet cut measures ¼-inch by ¼-inch and is about 2 to 3 inches long.'),
('Allumette Jardiniere', 'https://1.bp.blogspot.com/-gSCtMuSA9cE/YSX_5B0s_zI/AAAAAAAACZU/MYYjYWHZaagLArzGT6JGj002l3OdL4RCQCLcBGAsYHQ/s1920/Julienne-min.png', 'To allumette a vegetable means to cut it into small, thin pieces the size of matchsticks. If the vegetable is to be cooked, an allumette cut allows for a vegetable to cook rapidly and evenly, and integrate well into a mix of other ingredients, for instance in a sauce.'),
('Julienne', 'https://arbuz.com/wp-content/uploads/2018/11/How-To-Julienne-10.jpg', 'Julienne is a French cooking term for thin strips of vegetables (or meat or fruit). The strips are usually about 3 inches long and 1/16- to 1/8-inch thick.'),
('Rough Julienne', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTXcmAQWh_GGoZ9DTMsvxEvNeExWfuetoXnw&usqp=CAU', 'Rough Julienne is the shape and technique of cutting exactly the same as Julienne, but thicker. The length of a slice is up to 1.5 inches, thickness - from 2.7 to 3.9 inches.'),
('Macedoine / Large Dice', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxV5Tgx4HSHY0Yh41nesV5dJYdQ8Spdo8rmVwqeMPpYHtUDbJq6XSTiuAPH4PDSmQjOHc&usqp=CAU', 'A term used to describe the process of dicing ingredients into 3/4 inch cubes or a term that is used to describe a preparation of fruits or vegetables that have been diced (cubes that are 3/4 inch square) to be served either cold (raw) or hot (cooked).'),
('Medium Dice', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxV5Tgx4HSHY0Yh41nesV5dJYdQ8Spdo8rmVwqeMPpYHtUDbJq6XSTiuAPH4PDSmQjOHc&usqp=CAU', 'A term used to describe the process of dicing ingredients into 1/2 inch cubes or a term that is used to describe a preparation of fruits or vegetables that have been diced (cubes that are 1/2 inch square) to be served either cold (raw) or hot (cooked).'),
('Small Dice', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOXTjyFKpVTGSsWQLO4slv7vqhCxL8-zdo5hYCAs-OZDXrg5zZDXlMmxeUlSxyc72yynQ&usqp=CAU', 'A term used to describe the process of dicing ingredients into 1/4 inch cubes or a term that is used to describe a preparation of fruits or vegetables that have been diced (cubes that are 1/4 inch square) to be served either cold (raw) or hot (cooked).'),
('Paysanne', 'https://i.pinimg.com/originals/6b/b2/f1/6bb2f1b1e003a62637749587123cffea.jpg', 'A French term that is used to describe vegetables that have been cut into thin slices with shapes that correspond best to the shape of the vegetable.'),
('Chiffonade', 'https://theinspiredhome.imgix.net/images/chiffonade-knife-cuts.jpg?crop=focalpoint&fit=crop&fm=webp&fp-x=0.5&fp-y=0.5&q=80&w=845', 'To chiffonade is to cut thin strips of a flat leafy vegetable or larger leaf herb. It is a cutting technique that you can use with things like lettuces and very commonly basil, and it results in sliver-like curled strips that look very elegant when mixed into or strewn over various dishes.'),
('Rondelle / Slice', 'https://img.buzzfeed.com/buzzfeed-static/static/2019-01/4/10/asset/buzzfeed-prod-web-01/sub-buzz-15984-1546615417-1.jpg?resize=625:417', 'Also called rounds, a type of cut that creates round or oval, flat pieces by cutting a cylindrical vegetable crosswise. A regular crosswise cut produces a round slice and if the cut is made at an angle, it produces an oval slice.'),
('Diagonal / Oval Slice', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYP-SzTXc4s7RGAhy1vVGnHhdvISJBjWZXiw&usqp=CAU', 'Diagonal Cut. When diagonal cutting, the knife enters at a 45 ° angle. This method reduces cooking time because more surface is exposed to the heat, ensuring tenderness and an attractive shape.'),
('Brunoise / Mince', 'https://cdn.jwplayer.com/v2/media/7DNMRjKh/poster.jpg?width=720', 'The brunoise is the finest dice and is derived from the julienne. Any smaller and the cut is considered a mince. To brunoise, gather the julienned vegetable strips together, then dice into even 3mm cubes. This cut is most often used for making sauces like tomato concasse or as an aromatic garnish on dishes.'),
('Rolling Cut', 'https://res.cloudinary.com/hksqkdlah/image/upload/STP_KitchenNotes_HowToMakeARollCut_1437_hwihqw.jpg', 'Roll-cutting is used for long vegetables, such as Asian eggplant, carrots, and zucchini. It makes attractive chunks and exposes more of the surface area of the vegetable for faster cooking.'),
('Tourne', 'https://files.recipetips.com/images/glossary/t/tournee_cut_carrots.jpg', 'Tournée is French for the word turned and refers to a method of cutting and peeling root vegetables into oblong, seven-sided football-like shapes. The cut can be used for vegetables like carrots, turnips, and parsnips, or even zucchini and other types of summer squash.'),
('Mirepoix', 'https://theforkedspoon.com/wp-content/uploads/2019/11/11-02-19-2.jpg', 'Mirepoix (pronounced meer-uh-pwa) is a simple mix of coarsely chopped vegetables, onions, carrots and celery, the holy trinity of French cuisine. Many soups, sauces, stews, stocks and other dishes begin with mirepoix as the first building block of flavor.'),
('Crush', 'https://assets.epicurious.com/photos/5519aa9a6ec924e9311ce0c1/master/w_2106,h_1404,c_limit/EP-20150330-garlic-6x4-hires.jpg', 'A term used when piling the vegetable on one side of the board. Tilt the knife at a 30-degree angle to the board and drag it over the vegetable, scraping it across the surface of the board. Pile up the vegetable again, sprinkle lightly with salt, and scrape again. Repeat once or twice until the vegetable is a smooth paste.'),
('Wedges', 'https://www.stephgaudreau.com/wp-content/uploads/2019/05/roasted-potato-wedges-2.jpg', 'A term use to cut spherical vegetables and fruits lengthwise in sixths or eighths. Giving the vegetable or fruit a half u shape in appearance.'),
('Slit / Split', 'https://s3.amazonaws.com/finegardening.s3.tauntoncloud.com/app/uploads/vg-migration/2008/07/27233815/kg11-prepping_leeks-01.jpg', 'A term used when slicing the vegetable or fruit in half, mostly used for vegetable such as leeks, fennel, and string beans.');

INSERT INTO knives
(name, image, description)
VALUES
('Chef Knife', 'https://cdn.healthykitchen101.com/uploads/2018/02/The-Chef-Knives.jpg?w=1200&q=75', 'Also called a cooks knife, this is the most important blade in your kitchen. This knife typically has a broad blade tapering upward to a point, allowing it to rock back and forth for fast mincing. It can be anywhere between 6 and 12 inches long and the size is often chosen with consideration to how big the cooks hands are. The chef knife can be used for almost every cutting task in the kitchen, from cutting chicken to chopping carrots. That is why it is the must-have item in every kitchen knife set collection.'),
('Santoku Knife', 'https://cdn.healthykitchen101.com/uploads/2020/07/Santoku-Knife.jpg?w=1200&q=75', 'The Santoku knife is a Japanese version of the Western-style chefs knife. It is slightly shorter and thinner, and is used in place of the chefs knife by some cooks, especially those who prefer a smaller, lighter blade. Santoku means three virtues, which are slicing, dicing, and mincing. This knife is an all-rounder and can do almost everything a typical chefs knife can. Due to a flat blade, it does not rock on the cutting board. This makes it less suited for when you want to mince herbs, but a better choice for skinny slices of veggies.'),
('Utility Knife', 'https://cdn.healthykitchen101.com/uploads/2018/02/The-Utility-Knife.jpg?w=1200&q=75', 'Measuring between 4 and 7 inches in length, the utility knife is usually used for cutting food that is too small for a chefs knife. It is not great for chopping or slicing large items, but the narrow blade and small tip allows it to handle tasks such as thinner slicing, trimming, and filleting even better than a chefs knife.'),
('Kitchen Shears', 'https://cdn.healthykitchen101.com/uploads/2018/02/The-Kitchen-Shears.jpg?w=1200&q=75', 'Though shears are not technically a type of knives, they can be used in place of a knife. Kitchen shears are a pair of scissors with thick and strong blades to handle various food materials. They are useful for snipping herbs, sectioning chicken, preparing shrimp, octopus, and many other cutting tasks. For many home cooks, they are a favorite for slicing pizza. Some shears designed specifically for fast cutting of green onion or other herbs may have more than one blade. However, the blades on those shears are usually thin and weak. They also take more effort to sharpen than ordinary shears, which themselves are already picky about what type of knife sharpeners work on them.'),
('Boning Knife', 'https://cdn.healthykitchen101.com/uploads/2018/02/A-Boning-Knife.jpg?w=1200&q=75', 'The boning knife, as its name suggests, is used for separating meat from the bone, filleting fish, and cutting up meat. Smaller boning knives can also be used in place of a paring knife for peeling and trimming veggies. Boning knives are typically about 3 to 8 inches in length, with slightly varying blade widths. The blades can be Flexi, Semi-Flexi, or stiff, with stiff blades being the most popular among home cooks due to the enhanced precision of the cut.'),
('Bread Knife', 'https://cdn.healthykitchen101.com/uploads/2018/02/The-Bread-Knife.jpg?w=1200&q=75', 'Bread knives are used for cutting bread, cakes, and sometimes meat, poultry, and seafood. They are designed in a way that allows you to saw through the bread without pushing down or squishing it. Made to cut large chunks of food, the bread knife belongs to the longer spectrum of kitchen knives. It can be between 7 and 10 inches long. Its blade is narrow and straight (i.e. having no belly), and is always serrated, with big teeth along it.'),
('Cleaver Knife', 'https://cdn.healthykitchen101.com/uploads/2018/02/The-Cleaver-Knife.jpg?w=1200&q=75', 'A typical cleaver has a full tang, a thick spine and a very wide blade with little or no belly. This design allows it to cut through bones, meat, and hard and thick materials such as squash or pumpkin in a chopping motion. With a wide and heavy blade, the cleaver is also ideal for beating and pulverizing meat, poultry and fish, and crushing garlic.'),
('Paring Knife', 'https://cdn.healthykitchen101.com/uploads/2018/02/A-Paring-Knife.jpg?w=1200&q=75', 'If you love making garnishes for your food and drinks, the paring knife is a must-have. A paring knife usually comes with a thin 3 to 4 inch blade with a pointed tip. It can be used for cutting and peeling fruits and veggies, and trimming excess fat with great precision. The most common styles of paring knives include the spear point, sheeps foot, and birds beak, named after the shape of the tip.'),
('Steak Knife', 'https://cdn.healthykitchen101.com/uploads/2018/02/The-Steak-Knife.jpg?w=1200&q=75', 'Also called table knives, they are small knives that are used at the table for cooked food. They are great for steak, chicken, and fish. Steak knives can come with serrated, semi-serrated, or non-serrated edges. Serrated steak knives stay sharp for a longer period of time without honing or sharpening. Non-serrated knives become dull faster, but they are also easier to sharpen.'),
('Nakiri Bocho Knife', 'https://cdn.healthykitchen101.com/uploads/2018/02/The-Nakiri-Bocho.jpg?w=1200&q=75', 'The Nakiri bocho is a Japanese style knife used mostly for cutting vegetables. It features a thin and wide blade and squared-off tips. As it is designed for chopping veggies, the knife has a long straight blade. This allows it to cut long vegetables (eggplants or carrots, for example) in half with ease. It is the knife you should use when you want to make thin slices out of cucumber, bitter gourd, or tomatoes.'),
('Fillet Knife', 'https://cdn.healthykitchen101.com/uploads/2018/02/The-Fillet-Knife.jpg?w=1200&q=75', 'This knife looks very similar to the boning knife. However, there are subtle differences between the two. Since a boning knife is designed to remove meat from the bone, it tends to be thicker and have better force endurance. The fillet knife, meanwhile, is made to cut thin fish slices and thus is typically thinner, longer, and more flexible. The distinctions are so small the two knives can substitute each other in most cases. Knife makers sometimes blend the two, hence the emergence of the boning fillet knife. If you are an expert in sashimi or chicken boning, you would probably notice the differences. Other than that, either of the two should be sufficient for casual home cooking.');

INSERT INTO pots_pans
(name, image, description)
VALUES
('French Skillet', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRx_qhL_96Ce5bkCv3GdhrWuWjRyOLK1F1F1A&usqp=CAU', 'A french skillet is a pan for cooking that is essentially a combination of frying and sauté pans in shape. The sides of the skillet are flared outward, meaning they slope toward the bottom of the pan instead of going straight up.'),
('Fry Pan', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSR4AISayTFbQ7PCEGNF0Q4TMokwYXsTa7Gow&usqp=CAU', 'A Fry Pan is a flat-bottomed pan, usually about eight to 12 inches in diameter, with low outward flaring sides and a long handle. Modern-day Fry Pans are usually made out of stainless steel or aluminum; however, other materials used in its construction can include cast iron or copper as well.'),
('Wok', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStNpor1xnDG-imBX0rjmBa_q0mpkOl8c7bbw&usqp=CAU', 'A wok is a thin-walled cooking pan, shaped like a shallow bowl with handles, widely used in Chinese-style cooking. The wok has a round bottom that concentrates heat, cooking food quickly with relatively little oil.'),
('Grill Pan', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzddYPWCU8gkaNQGYwRYTV9yIGxMUjqRqiSQ&usqp=CAU', 'A grill pan is a wide, shallow metal vessel used to contain food that is being cooked under a grill.'),
('Sauce Pan', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSc06k7Faj--Lch9TR8Mi07dLR2qcCzjXGX2Q&usqp=CAU', 'A saucepan is a deep stovetop pan with a long handle and, usually, a lid. You might use a saucepan to cook sauce, or for the macaroni from your box of macaroni and cheese. Saucepans are made out of various materials, from stainless steel and aluminum to copper and enamel-coated metal.'),
('Saucier', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhi3_AH9Z4Lg8RJjvcQEawU-7JkOnsYkUYKQ&usqp=CAU', 'As a shorter and different shaped version of a sauce pan, the saucier is a pan often used for preparations requiring more repetitive motions with the ingredients in the pan, such as stirring or whisking.'),
('Double Boiler', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHMMKA-kOj3a_Hoa8NHBGe2qayf0LXBRXxgg&usqp=CAU', 'A double boiler is a cooking utensil consisting of two saucepans fitting together so that the contents of the upper can be cooked or heated by boiling water in the lower.'),
('Saute Pan', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLVnqqhWdCSCY8rbmXFRv0WswIndVpz2dGvg&usqp=CAU', 'A sauté pan, from the French verb meaning to jump (sauter), has a wide, flat bottom and relatively tall, vertical sides.'),
('Multi Pot', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpKDb7Tn-glfTIsXkFUWMEmAlzVTlp5cgvbw&usqp=CAU', 'A multi pot is also known as a  multifunction cooker that allows you to steam your favorite vegetables, cook pasta and use it as a large stock pot.'),
('Soup Pot or Stock Pot', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStLMIIsZfIZp3eUUbpUpxoz5Bc12wHaF0K1g&usqp=CAU', 'A large, deep pot that is most often used to make stock, soup, stew, chili, and to boil noodles, pasta, corn, vegetables, and seafood. Commonly made of stainless steel, Stockpots are available in a variety of sizes from 8 quart to 36 quarts for general home use and larger sizes for commercial use.'),
('Roaster Pan', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQS27gDbq8gntj7OWvR2RPTMyT-vLj2NsKt2A&usqp=CAU', 'A roasting pan is a piece of cookware used for roasting meat in an oven, either with or without vegetables or other ingredients. A roasting pan may be used with a rack that sits inside the pan and lets the meat sit above the fat and juice drippings.'),
('Braiser', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSraPDgsoGN5Gso5pK2mEjepwhkNkfkwG-zYg&usqp=CAU', 'A brasier is similar to a french oven in shape and appearance but about 2 to 3 inches in height. It is good for making gravies and such since it holds heat extremely well.'),
('French Oven', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS412kbsXFoh0UQJpnd2rO3er2hmUZIwCcc-w&usqp=CAU', 'French ovens are used to cooking and baking a variety of dishes. A French oven is the name for a large pot used for cooking and baking. This pot can be fairly large and round, with a flat bottom and often comes with a tight fitting lid.'),
('Cast Iron Pan or Deep Skillet', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTszS1GUajHh7YSm9iWVg522ieq3UcmvzZgoQ&usqp=CAU', 'A cast iron, an alloy of iron that contains 2 to 4 percent carbon, along with varying amounts of silicon and manganese and traces of impurities such as sulfur and phosphorus. It is made by reducing iron ore in a blast furnace.');

INSERT INTO cooking_styles
(name, image, description)
VALUES
('Grilling', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRO8N3EM4gcLVyHD_jZNDyHZ867Z3_AJPHFIQ&usqp=CAU', 'Grilling involves cooking food on a rack over a heat source, usually a charcoal fire or ceramic briquettes heated by gas flames. Direct heat quickly sears the outside of food, producing distinctive robust, roasted and sometimes pleasantly charred flavors and a nice crust.'),
('Broiling', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcqyB9dyRJT4Hf2g4mV2rKMDXvt9EJ2xdbFPprb1EGN4CEuCaFL1SVAmUES1pwtWUlPRI&usqp=CAU', 'Broiling involves cooking by exposing food to direct radiant heat, either on a grill over live coals or below a gas burner or electric coil. Broiling differs from roasting and baking in that the food is turned during the process so as to cook one side at a time.'),
('Baking', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQUfBxp7CE09V6vRQOLhodS884DtCRa5pFiMafGdR1VQ41jOhDqdZd8s-En4vs49M_zM4&usqp=CAU', 'Baking is a process of cooking by dry heat, especially in some kind of oven. It is probably the oldest cooking method. Bakery products, which include bread, rolls, cookies, pies, pastries, and muffins, are usually prepared from flour or meal derived from some form of grain.'),
('Roasting', 'http://pediaa.com/wp-content/uploads/2015/12/Difference-Between-Roasting-and-Baking-image-2.jpg', 'Roasting is a slow-cooking process, using indirect, diffused heat to cook its ingredients. It is a dry-heat cooking method where hot air surrounds the food and cooks it evenly on all sides at a temperature of at least 300 °F (or 150 °C). The heat can also be derived from an open flame, an oven, or another heat source.'),
('Sauteing', 'https://www.wikihow.com/images/thumb/2/2d/Saut%C3%A9-Step-10-preview.jpg/550px-nowatermark-Saut%C3%A9-Step-10-preview.jpg', 'Sauteing is a method of cooking that uses a relatively small amount of oil or fat in a shallow pan over relatively high heat. There are various saute methods such as tossing or stiring the items in a pan large enough to hold all the ingredients.'),
('Searing', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSsKBKt49q_JiYLaH7hPJxmIPFn3mjT8Af-jYG9AIaqzFbWCT9Nl0w-lbd9zd7fCkfPcA&usqp=CAU', 'Searing (or pan searing) is a technique used in grilling, baking, braising, roasting, sautéing, etc., in which the surface of the food (usually meat: beef, poultry, pork, seafood) is cooked at high temperature until a browned crust forms on both sides and around the outside edges.'),
('Frying', 'https://ireallylikefood.com/wp-content/uploads/2019/11/fry-at-home-1200x675.jpg', 'Frying is the process which involves the cooking of food in hot fats or oils, usually done with a shallow oil bath in a pan over a fire or as so-called deep fat frying, in which the food is completely immersed in a deeper vessel of hot oil.'),
('Boiling', 'https://cdn.cdnparenting.com/articles/2019/02/28170828/1060532033-H.webp', 'Boiling is the process by which a liquid turns into a vapor when it is heated to its boiling point. The change from a liquid phase to a gaseous phase occurs when the vapor pressure of the liquid is equal to the atmospheric pressure exerted on the liquid.'),
('Poaching', 'https://www.finedininglovers.com/sites/g/files/xknfdk626/files/2020-09/23_Poaching_an_egg_%C2%A9_stockFood.jpg', 'Poaching is a moist heat method of cooking by submerging food in some kind of liquid and heating at a low temperature. This is a technique that is used to cook delicate proteins such as fish, chicken, and eggs, as well as some fruits and vegetables.'),
('Steaming', 'https://www.lkkprofessional.com/images/inspiration/main/steaming-prep_webgrid.jpg', 'Steaming is a method of cooking that requires moist heat. The heat is created by boiling water which vaporizes into steam. The steam brings heat to the food and cooks it. Unlike boiling, the food is separate from the water and only comes into direct contact with the steam.'),
('Blanching', 'https://hotcheapeasy.files.wordpress.com/2011/09/2011-emmes-bday-freezing-tomatoes-029.jpg', 'Blanching is scalding vegetables in boiling water or steam for a short time. It is typically followed by quick, thorough cooling in very cold or ice water. Blanching stops enzyme actions which otherwise cause loss of flavor, color and texture.'),
('Sous Vide', 'https://res.cloudinary.com/jerrick/image/upload/v1612828429/6021cf0d00a546001cd52078.jpg', 'Sous vide is a low-temperature cooking method where food is vacuum-sealed and slowly cooked in a water bath. French for under vacuum, sous vide uses heated water to gently cook food so that it stays juicy and flavorful. The water temperature is well below simmering, anywhere from 125 degrees F to 195 degrees F.');
